version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: userdata
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data:/var/lib/mysql